{% set name = "pyexcel-ezodf" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 972eeea9b0e4bab60dfc5cdcb7378cc7ba5e070a0b7282746c0182c5de011ff1

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - lxml

test:
  requires:
    - python {{ python_min }}
  imports:
    - ezodf

about:
  home: https://github.com/pyexcel/pyexcel-ezodf
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python package to create/manipulate OpenDocumentFormat files
  description: |
    ezodf is a Python package to create new or open existing
    OpenDocument (ODF) files to extract, add, modify or delete document data
    forked from dead project https://bitbucket.org/mozman/ezodf
    format and to/from databases
  dev_url: https://github.com/pyexcel/pyexcel-ezodf

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
